// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjkEoh-RdeybNQ-dJdbor3tN3XIz82xE',
    appId: '1:777822275786:web:1234567890abcdef',
    messagingSenderId: '777822275786',
    projectId: 'grade-2f7fc',
    authDomain: 'grade-2f7fc.firebaseapp.com',
    storageBucket: 'grade-2f7fc.appspot.com',
    databaseURL: 'https://grade-2f7fc-default-rtdb.europe-west3.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjkEoh-RdeybNQ-dJdbor3tN3XIz82xE',
    appId: '1:777822275786:android:1234567890abcdef',
    messagingSenderId: '777822275786',
    projectId: 'grade-2f7fc',
    storageBucket: 'grade-2f7fc.appspot.com',
    databaseURL: 'https://grade-2f7fc-default-rtdb.europe-west3.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKjkEoh-RdeybNQ-dJdbor3tN3XIz82xE',
    appId: '1:777822275786:ios:1234567890abcdef',
    messagingSenderId: '777822275786',
    projectId: 'grade-2f7fc',
    storageBucket: 'grade-2f7fc.appspot.com',
    databaseURL: 'https://grade-2f7fc-default-rtdb.europe-west3.firebasedatabase.app',
    iosClientId: '777822275786-1234567890abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.grade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKjkEoh-RdeybNQ-dJdbor3tN3XIz82xE',
    appId: '1:777822275786:macos:1234567890abcdef',
    messagingSenderId: '777822275786',
    projectId: 'grade-2f7fc',
    storageBucket: 'grade-2f7fc.appspot.com',
    databaseURL: 'https://grade-2f7fc-default-rtdb.europe-west3.firebasedatabase.app',
    iosClientId: '777822275786-1234567890abcdef.apps.googleusercontent.com',
    iosBundleId: 'com.example.grade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKjkEoh-RdeybNQ-dJdbor3tN3XIz82xE',
    appId: '1:777822275786:windows:1234567890abcdef',
    messagingSenderId: '777822275786',
    projectId: 'grade-2f7fc',
    authDomain: 'grade-2f7fc.firebaseapp.com',
    storageBucket: 'grade-2f7fc.appspot.com',
    databaseURL: 'https://grade-2f7fc-default-rtdb.europe-west3.firebasedatabase.app',
  );
}
